#!/bin/bash
#
# make sure git is installed
hash git 2> /dev/null || sudo apt-get install -y git
#
# Update installer
git clone https://github.com/reinzor/server.git ~/.server
#
# Add environment to bashrc
"source ~/.server/env/env.bash" >> ~/.bashrc
#
# Source bashrc to setup environment
source ~/.bashrc
